### ISSUE TITLE
South Petherton Group Does Not Show On Map

### ISSUE THREAD

**Issue by conatus** [Covid-Mutual-Aid/search-by-postcode#13]
The South Petherton group, which is on the spreadsheet, does not show on the map.

It's on the spreadsheet 3 or 4 times. Suspect this is because there is bug in the way these entries are de-duplicated, which is meaning that it isn't clear.

<img width="845" alt="Screenshot 2020-03-26 at 08 49 25" src="https://user-images.githubusercontent.com/317734/77627691-2b66c680-6f3f-11ea-9413-e66c24cd93f7.png">

Interim solution is to remove the duplication on the spreadsheet side.

**Comment by tapjay** [comment]
@conatus am currently manually updating the map to make sure the google sheet columns haven't moved. I've since updated the groups so it is now appearing properly.
