### ISSUE TITLE
Treat Mutual Aid spreadsheet as single source of truth for now

### ISSUE THREAD

**Issue by conatus** [Covid-Mutual-Aid/search-by-postcode#6]
The groups at the moment are read from the Mutual Aid spreadsheet, but when they are written via the Add Group link on this map, they only end up in the DynamoDB.

As far as I can see from the Lambda, there isn't a write back to the Google Sheet right now.
https://github.com/Covid-Mutual-Aid/search-by-postcode/blob/051a54aa257739f979cc297dff44e3a0274eca42/lambdas/services/database/handler.ts#L67-L71

The Google Sheet is widely shared throughout Facebook and I think does need to be kept in sync.

A good suggestion before sharing this more widely might be:
1. Replace writing to DynamoDB with a simple link to [the form to add to the spreadsheet](https://docs.google.com/forms/d/e/1FAIpQLSdJrgqHazomhDsJDG3Nnye30Ys7sZEl-APCrQh80D1g-iQrgQ/viewform). Treating the spreadsheet as a single source of truth.
2. Come back to this and create an additional Lambda to enable sync from DynamoDB to Google Sheets.

**Comment by tapjay** [comment]
Yes that's a good point, we will defer to the sheets for now. It would be good eventually use the DB as the main source so we can dedupe entries and ensure more specific locations for the groups, but it's definitely important that we don't disrupt existing process.

**Comment by conatus** [comment]
Great! Don't forget we've got some tooling for deduping over here. We cut the Facebook URLs down a bit, by normalising them, and use this to dedupe.

https://github.com/commonknowledge/covid-19-mutual-aid-list-sync

**Comment by tapjay** [comment]
Thanks, we are already doing this! We have been normalising and deduping on the path portion of the facebook url as well as exact matches on location and group name. If you are interested, the code is here [lambdas/services/lib/utils.ts](https://github.com/Covid-Mutual-Aid/search-by-postcode/blob/master/lambdas/services/lib/utils.ts)

**Comment by conatus** [comment]
Can't believe @Pingid wrote their own `uniqueBy` - we just used Lodash. 😂 

The normalisation code is quite similar. The difference is we also convert from `m.facebook.com` URLs to desktop URLs as this was a problem with the list. People have been pretty loose with the location name, so [this code](https://github.com/Covid-Mutual-Aid/search-by-postcode/blob/master/lambdas/services/lib/utils.ts#L150) may yield some unexpected results.

https://github.com/commonknowledge/covid-19-mutual-aid-list-sync/blob/master/src/urls.js#L3-L10

There is a test suite here - https://github.com/commonknowledge/covid-19-mutual-aid-list-sync/blob/master/src/__tests__/urls.test.js

**Comment by conatus** [comment]
Happy to spin out a new issue for this deeper denormalisation based on mobile versus desktop Facebook.

**Comment by tapjay** [comment]
@conatus yes please open another issue on the deduping so that the discussions can be more easily tracked.

**Comment by Pingid** [comment]
> Can't believe @Pingid wrote their own `uniqueBy` - we just used Lodash. 😂
> 
> The normalisation code is quite similar. The difference is we also convert from `m.facebook.com` URLs to desktop URLs as this was a problem with the list. People have been pretty loose with the location name, so [this code](https://github.com/Covid-Mutual-Aid/search-by-postcode/blob/master/lambdas/services/lib/utils.ts#L150) may yield some unexpected results.
> 
> https://github.com/commonknowledge/covid-19-mutual-aid-list-sync/blob/master/src/urls.js#L3-L10
> 
> There is a test suite here - https://github.com/commonknowledge/covid-19-mutual-aid-list-sync/blob/master/src/__tests__/urls.test.js

Haha ye habit i guess.

We are using the URL node library to get parse the urls then comparing the pathnames. Which seems to solve this issue I have manually gone through quite a number of the urls to see and it seems to work.

```
const { parse } = require('url')
const normaliseLink = (x) => parse(x).pathname.replace(/\/$/, '')
```
