### ISSUE TITLE
Map not appearing on ancient devices

### ISSUE THREAD

**Issue by NickCNickCNickC** [Covid-Mutual-Aid/search-by-postcode#8]
I have tested on two very old devices (an htc Desire C (Android 4.0.3) and an Archos 80 tablet (Android 4.1.1)) and I can't get the map to work within the web page. The surrounding controls and map frame appear then disappear.

Both devices are running the latest Chrome and Maps that they can support.

This is not critical - a link on the page takes me to Google Maps which presents the info and works ok so I have a way out,

**Comment by tapjay** [comment]
I've since added polyfills for Promise and fetch, is there a chance that this resolved the issue?

**Comment by NickCNickCNickC** [comment]
Still no joy in afraid.
These are seriously old devices though, and the chance of anything like this existing in the wild is slim. And the workaround of following the link to Maps is acceptable.
So basically, if you're inclined to keep thinking I'll keep testing, but don't sweat over it - every other device I tried worked (Android 7 to 9, Windows 10, Windows Mobile. Sorry I can't test on Apples from here though.). Cheers!

**Comment by tapjay** [comment]
Ah that is unfortunate. Thanks so much for taking the time to test though, much appreciated! Closing this for now.
